Controllers/CarrinhoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using projetofood.Models;
using projetofood.Repositories.Interfaces;
using projetofood.ViewModel;

namespace projetofood.Controllers
{
    [Authorize]
    public class CarrinhoController : Controller
    {
        private readonly Carrinho _carrinho;
        private readonly IItemRepository _itemRepository;
        public CarrinhoController(Carrinho carrinho, IItemRepository itemRepository)
        {
            _carrinho = carrinho;
            _itemRepository = itemRepository;
        }
        public IActionResult Index()
        {
            var itens = _carrinho.GetCarrinhoCompraItems();
            _carrinho.CarrinhoItens = itens;
            var carrinhoVM = new CarrinhoViewModel
            {
                Carrinho = _carrinho,
                CarrinhoTotal = _carrinho.GetCarrinhoCompraTotal()
            };
            return View(carrinhoVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int itemId)
        {
            var itemSelecionado = _itemRepository.Itens.FirstOrDefault(l => l.ItemId == itemId);
            if (itemSelecionado != null)
            {
                _carrinho.AdicionarItemCarrinho(itemSelecionado);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverCarrinho(int itemId)
        {
            var itemSelecionado = _itemRepository.Itens.FirstOrDefault(l => l.ItemId == itemId);
            if (itemSelecionado != null)
            {
                _carrinho.RemoverItemDoCarrinhoCompra(itemSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using projetofood.Models;
using projetofood.Repositories;
using projetofood.Repositories.Interfaces;
using projetofood.ViewModel;

namespace projetofood.Controllers
{

  
    public class ItemController : Controller
    {
        private readonly IItemRepository _itemRespository;
        public ItemController(IItemRepository itemRepository)
        {
            _itemRespository = itemRepository;
        }
        public IActionResult List(string categoria)
        {
            IEnumerable<Item> itens;
            var categoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(categoria))
            {
                itens = _itemRespository.Itens.OrderBy(m => m.ItemId);
                categoriaAtual = "Todos os itens";
            }
            else
            {
                itens = _itemRespository.Itens.Where(m =>
                m.Categoria.Nome.Equals(categoria)).OrderBy(m => m.ItemId);

                categoriaAtual = categoria;
            }
            var itemListViewMovel = new ItemListViewModel
            {
                Itens = itens,
                CategoriaAtual = categoriaAtual
            };
            return View(itemListViewMovel);
        }
        public IActionResult Details(int itemId)
        {

            var item = _itemRespository.Itens.FirstOrDefault(m =>

            m.ItemId == itemId);

            return View(item);
        }
        public IActionResult Search(string searchString){

IEnumerable<Item> itens;
string categoriaAtual = string.Empty;
if(string.IsNullOrEmpty(searchString)){
itens = _itemRespository.Itens.OrderBy(m=> m.Nome);
categoriaAtual = "Todos os Itens";
}
else{
itens = _itemRespository.Itens.Where(m =>
m.Nome.ToLower() == searchString.ToLower()).OrderBy(m => m.Nome);

if(itens.Any()){
categoriaAtual = "Itens";
}
else{
categoriaAtual = "Nada encontrado";
}
}
return View("~/Views/Item/List.cshtml", new
ItemListViewModel{ CategoriaAtual = categoriaAtual,
Itens = itens });

}
    }
}

Views/Shared/_Card.cshtml
<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemPequenaUrl" class="img-fluid" asp-append-version="true"></p>
    <h3>Preço : @Model.Preco.ToString("c")</h3>
    <h4>
        <a asp-controller="Item" asp-action="Details" asp-route-itemId="@Model.ItemId">@Model.Nome</a>
    </h4>
    <p>@Model.DescricaoCurta</p>
    <div>
        <p class="button">
            <a class="btn btn-warning" id="cartButton" asp-controller="Carrinho"
                asp-action="AdicionarItemNoCarrinhoCompra" asp-route-itemId="@Model.ItemId">
                Incluir no Carrinho
            </a>
        </p>
    </div>
</div>

Views/Shared/_Carousel.cshtml
<div id="carouselMoveis" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/imagens/sorvete20.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/sorvete20.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/sorvete20.png" class="d-block w-100" alt="...">
        </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselMoveis" data-bs- slide="prev">

        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
    </button>

    <button class="carousel-control-next" type="button" data-bs-target="#carouselMoveis" data-bs- slide="next">

        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Próxima</span>
    </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IceCream</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projetofood.styles.css" asp-append-version="true" />
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <img src="~/imagens/logo.png">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IceCream</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin"))
                            {

                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>

                            }
                        </li>
                        <li class="nav-item ">

                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        <li>
                            @await Html.PartialAsync("_Login")
                        </li>
                        <li class="nav-item">

                            <form class="navbar-form navbar-right" asp-controller="Item" asp-action="Search"
                                method="get">

<div class="form-group">
<input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
</div>
</form>
</li>
@await Component.InvokeAsync("CarrinhoResumo")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-success">
        <div class="container">
        <a asp-area="" asp-controller="Home" asp-action=""></a>
      <div class="row">
        <div class="col">
        <h5><i class="bi bi-geo-alt-fill"></i>Endereço</h5>
        Rua das Acácias,
        EMAIL: reserva2000@gmail.com
        </div>
       <div class="col">
        <h5><i class="bi bi-telephone-fill"></i>Reservas</h5>
        (18)99999-9999
        Araçatuba-SP
        </div>
       <div class="col">
        <h5><i class="bi bi-clock"></i>Aberto</h5>
        TER-DOM:18h - 00h
        </div>
        <div class="col">
            <h5>SEGUIR</h5>
        <i class="bi bi-instagram fs-2"></i> <i class="bi bi-facebook fs-2"></i>
        <i class="bi bi-twitter fs-2"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Login.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<UserAcount> SignInManager

@if (SignInManager.IsSignedIn(User))

{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-left">
        <ul class="nav navbar-nav navbar-left">
            <button type="submit" style="width:auto" class="nav-link btn btn-link">
                <strong> Logout : @User.Identity.Name &nbsp; </strong>
            </button>
        </ul>
    </form>
}

else
{
    <ul class="nav navbar-nav navbar-left">

        <a class="nav-link text-light" asp-controller="Account" asp-action="Login"
            asp-route-returnUrl="@string.Format("{0}{1}",Context.Request.Path, Context.Request.QueryString)"
            style="color:black">&nbsp; Login&nbsp; </a>
        <a class="nav-link text-light" asp-controller="Account" asp-action="Register"
            style="color:black">&nbsp;Cadastre-se&nbsp;&nbsp;&nbsp;</a>
    </ul>
}