Models/Carrinho.cs
using Microsoft.EntityFrameworkCore;
using projetofood.Context;

namespace projetofood.Models
{
    public class Carrinho
    {
        private readonly AppDbContext _context;
        public Carrinho(AppDbContext context)
        {
            _context = context;
        }

        public string CarrinhoId { get; set; }
        public List<CarrinhoItem> CarrinhoItens { get; set; }
        public static Carrinho GetCarrinhoCompra(IServiceProvider
        services)
        {

            ISession session =

            services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<AppDbContext>();
            string carrinhoId = session.GetString("CarrinhoId") ??

            Guid.NewGuid().ToString();

            session.SetString("CarrinhoId", carrinhoId);
            return new Carrinho(context)
            {
                CarrinhoId = carrinhoId
            };

        }
        public void AdicionarItemCarrinho(Item item)
        {
            var carinhoItem = _context.CarrinhoItens.SingleOrDefault(s =>

        s.Item.ItemId == item.ItemId && s.CarrinhoId == CarrinhoId);

            if (carinhoItem == null)
            {
                carinhoItem = new CarrinhoItem
                {
                    CarrinhoId = CarrinhoId,
                    Item = item,
                    Quantidade = 1
                };
                _context.CarrinhoItens.Add(carinhoItem);
            }
            else
            {
                carinhoItem.Quantidade++;
            }
            _context.SaveChanges();
        }
        public int RemoverItemDoCarrinhoCompra(Item item)
        {
            var carrinhoQuantidade = 0;
            var carinhoItem = _context.CarrinhoItens.SingleOrDefault(s =>

            s.Item.ItemId == item.ItemId && s.CarrinhoId == CarrinhoId);

            if (carinhoItem != null)
            {
                if (carinhoItem.Quantidade > 1)
                {
                    carinhoItem.Quantidade--;
                    carrinhoQuantidade = carinhoItem.Quantidade;
                }
                else
                {
                    _context.CarrinhoItens.Remove(carinhoItem);
                }

            }
            _context.SaveChanges();
            return carrinhoQuantidade;
        }
        public List<CarrinhoItem> GetCarrinhoCompraItems()
        {
            return CarrinhoItens ?? _context.CarrinhoItens.Where(c =>

            c.CarrinhoId == CarrinhoId).Include(s => s.Item).ToList();
        }
        public void LimparCarrinho()
        {
            var carrinhoCompra = _context.CarrinhoItens.Where(c =>

        c.CarrinhoId == CarrinhoId);

            _context.CarrinhoItens.RemoveRange(carrinhoCompra);
            _context.SaveChanges();
        }
        public double GetCarrinhoCompraTotal()
        {
            List<double> total = _context.CarrinhoItens.Where(_c => _c.CarrinhoId == CarrinhoId).Select(c => c.Quantidade * c.Item.Preco).ToList();
            double totalr = 0;
            foreach (double t in total)
            {
                totalr = totalr + t;
            }
            return totalr;
        }
    }
}

Controllers/CarrinhoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using projetofood.Models;
using projetofood.Repositories.Interfaces;
using projetofood.ViewModel;

namespace projetofood.Controllers
{
    [Authorize]
    public class CarrinhoController : Controller
    {
        private readonly Carrinho _carrinho;
        private readonly IItemRepository _itemRepository;
        public CarrinhoController(Carrinho carrinho, IItemRepository itemRepository)
        {
            _carrinho = carrinho;
            _itemRepository = itemRepository;
        }
        public IActionResult Index()
        {
            var itens = _carrinho.GetCarrinhoCompraItems();
            _carrinho.CarrinhoItens = itens;
            var carrinhoVM = new CarrinhoViewModel
            {
                Carrinho = _carrinho,
                CarrinhoTotal = _carrinho.GetCarrinhoCompraTotal()
            };
            return View(carrinhoVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int itemId)
        {
            var itemSelecionado = _itemRepository.Itens.FirstOrDefault(l => l.ItemId == itemId);
            if (itemSelecionado != null)
            {
                _carrinho.AdicionarItemCarrinho(itemSelecionado);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverCarrinho(int itemId)
        {
            var itemSelecionado = _itemRepository.Itens.FirstOrDefault(l => l.ItemId == itemId);
            if (itemSelecionado != null)
            {
                _carrinho.RemoverItemDoCarrinhoCompra(itemSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/PedidoController.cs
using projetofood.Models;
using projetofood.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;

namespace projetofood.Controllers
{
    [Authorize]
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoR;
        private readonly Carrinho _carrinho;
        public PedidoController(IPedidoRepository pedidoR, Carrinho carrinho)
        {
            _pedidoR = pedidoR;
            _carrinho = carrinho;
        }
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;
            //obtem os itens do carrinho de compra do cliente
            List<CarrinhoItem> items = _carrinho.GetCarrinhoCompraItems();
            _carrinho.CarrinhoItens = items;
            //verifica se existem itens de pedido
            if (_carrinho.CarrinhoItens.Count == 0)
            {
                ModelState.AddModelError("", "Seu carrinho esta vazio, que tal incluir um lanche...");
            }
            //calcula o total de itens e o total do pedido
            foreach (var item in items)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += (Convert.ToDecimal(item.Item.Preco) * item.Quantidade);
            }
            //atribui os valores obtidos ao pedido
            pedido.TotalItensPedido = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;
            //valida os dados do pedido
            if (ModelState.IsValid)
            {
                //cria o pedido e os detalhes
                _pedidoR.CriarPedido(pedido);
                //define mensagens ao cliente
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido :)";
                ViewBag.TotalPedido = _carrinho.GetCarrinhoCompraTotal();
                //limpa o carrinho do cliente
                _carrinho.LimparCarrinho();
                //exibe a view com dados do cliente e do pedido
                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }
            return View(pedido);
        }
    }
}

Views/Carrinho/Index.cshtml
@model CarrinhoViewModel
<div class="Container">
    <div class="row checkoutForm">
        <div>
            <img src="~/images/Full-Cart-icon.png" width="30" height="35" />
            <h4>Seu carrinho de compras : </h4>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Quantidade</th>
                    <th>Item</th>
                    <th class="text-right">Preço</th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Carrinho.CarrinhoItens)
                {
                    <tr>
                        <td class="text-center">@item.Quantidade</td>
                        <td class="text-left">@item.Item.Nome</td>
                        <td class="text-right">@item.Item.Preco.ToString("c")</td>
                        <td class="text-right">
                            @((item.Quantidade * item.Item.Preco).ToString("c"))
                        </td>
                        <td class="text-center">
                            <a asp-controller="Carrinho" asp-action="RemoverCarrinho"
                                asp-route-itemId="@item.Item.ItemId"><img src="~/images/remover.png" width="20px"
                                    height="20px" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total:</td>
                    <td class="text-right">
                        @Model.CarrinhoTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group">
                <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar
                    Pedido</a>

                &nbsp;&nbsp;&nbsp;
                <a class="btn btn-primary" asp-controller="Movel" asp-action="List">Continuar
                    Comprando</a>
            </div>
        </div>
        <br />
    </div>
</div>